### ISSUE TITLE
White rectangle behind view wrapped by Link

### ISSUE THREAD

**Issue by amadeu01** [frzi/SwiftUIRouter#10]
I'm not really sure if it is something in the lib or I just messed things.

When I try something like:

```
ForEach(pipes, id: \.id) { pipe in
                Link(to: "/pipe/:" + pipe.id) {
                    PipeCell(pipe: pipe).frame(
                        width: pipeCellSize.width,
                        height: pipeCellSize.height,
                        alignment: .center
                    )
                }
            }
```

I get this:

![image](https://user-images.githubusercontent.com/11631092/88744829-e20dca00-d11e-11ea-937b-b8ee4f336c7f.png)

`Link` seems to display this weird white rectangle behind the view. I'm not sure how I should use it.

**Comment by amadeu01** [comment]
I've also tried stuff like:

```swift
Link(to: "/pipe/:" + pipe.id) {
                    VStack(alignment: .leading) {
                        Text("Text")
                        Text("Text")
                        Text("Text")
                        Text("Text")
                    }
                }.padding().background(Color.green)
```

Which resulted in 
![image](https://user-images.githubusercontent.com/11631092/88745515-a1af4b80-d120-11ea-99b8-8f4439e42b08.png)

**Comment by frzi** [comment]
SwiftUI Router's `Link` is basically just a wrapper around a `Button`. Could you try the following?
```swift
Link(to: "/pipe/:" + pipe.id) {
    // Etc ...
}
.buttonStyle(PlainButtonStyle())
```
This _should_ erase any predefined styling of a Button.
