### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by AylaAsia-qinsunbo** [frzi/SwiftUIRouter#32]
Hello, thank you for the library. But because there is no example, I don't know how to use it. Can you provide an example? thanks

**Comment by frzi** [comment]
Hi, yes, sorry, I understand the library can be a bit alien and daunting at first.

First you wrap your app in a `Router`:
```swift
@main
struct MyApp: App {
	var body: some Scene {
		WindowGroup {
			Router {
				ContentView()
			}
		}
	}
}
```
The `Router` initializes all environment values and object etc. So using routes only works inside a `Router`. (You only need one `Router` in your entire app.)

Use `Route` to only render views when their path matches that of the global state. And use `NavLink` to make buttons that navigate to a path.
```swift
struct MyView: View {
	var body: some View {
		VStack {
			Route(path: "/hello-world") {
				// Will only be rendered if the path is "/hello-world".
				Text("Hello world!")
			}

			// A button that will navigate to "/hello-world"
			NavLink(to: "/hello-world") {
				Text("Go to Hello world")
			}
		}
	}
}
```

These are the basics. The README contains short descriptions of other views and features available in the library. The source code also contains documentation and is accessible in Xcode. (You may have to build the documentation via *Product > Build Documentation* to get access to the fully formatted docs)

<img width="507" alt="Schermafbeelding 2021-11-05 om 12 07 04" src="https://user-images.githubusercontent.com/8537579/140501463-fdd780c0-f36e-4b02-b837-6f01ea365ea1.png">

I'm still trying to reserve time to work on tutorial(s) and example code 🙇

**Comment by AylaAsia-qinsunbo** [comment]
Thank you
