### ISSUE TITLE
How to navigate to any page

### ISSUE THREAD

**Issue by liziyang0625** [frzi/SwiftUIRouter#37]
Hello, I am new to SwiftUI, I have a page A with a Button, when I press the Button, I want navigate to PageB, I don't know how to write the Route, can you help me, thanks.

**Comment by frzi** [comment]
Hi 👋 

A quick example can be found in #32 (How to use).

**Comment by frzi** [comment]
With the release of 1.3.0 a small set of examples have been created. They can be found in [their own repository](https://github.com/frzi/SwiftUIRouter-Examples).
