### ISSUE TITLE
Type safe routes

### ISSUE THREAD

**Issue by denizdogan** [frzi/SwiftUIRouter#50]
Currently, I'm doing this:

```
enum AppRoutes {
    static let splash = "/"
    static let login = "/login"
    static let feed = "/feed"
}

SwitchRoutes {
    Route(AppRoutes.splash) {
        SplashScreenView()
    }
    Route(AppRoutes.feed) {
        FeedView()
    }
    ...
}
```

Is there any way to make this properly type safe, or at least _safer_? It seems rather fragile to rely on strings in this manner. Ideally, I wouldn't want to define my own "route enum" and have `navigator.navigate` accept only that type, etc.

**Comment by denizdogan** [comment]
@frzi Makes sense, thank you!

**Comment by denizdogan** [comment]
@frzi I can't seem to figure out what the `Route` init would look like when using `enum AppRoute` with associated values on some of the cases. Am I right in suspecting that it's not simple?

**Comment by frzi** [comment]
You'll probably want the paths for `Route`s to be formed differently. As an example:

```swift
enum AppRoute {
	case news(id: UUID? = nil)

	// Read this property in `NavLink` and `Navigator.navigate()`
	var path: String {
		switch self {
		case .news(let id): return "/news/\(id?.uuidString ?? "")"
		}
	}

	// Read this property in `Route`
	var route: String {
		switch self {
		case .news(let id): return "/news/\(id?.uuidString ?? ":id?")"
		}
	}
}

Route(.news()) { /* ... */ } // For `/news/:id?`
Route(.news(someConstantUUID)) { /* ... */ } // For `/news/edc54f97-ff00-463a-8897-f75144e41b7b` or something
```

With a bit of imagination I'm sure you'll be able to come up with a solution that fits your needs perfectly. 😄
