### ISSUE TITLE
Full screen navigation above tabView

### ISSUE THREAD

**Issue by IlyasNN** [frzi/SwiftUIRouter#60]
How can I Create one more navigation stack above tabView?

So I need to present a few different flows under each of tab. But I can't fine approach to do that. I had a look in examples and there is no scenario I need. 

I'll explain using one of examples:
From one of the tabs I what to navigate further:
<img width="484" alt="Screenshot 2022-11-07 at 18 52 43" src="https://user-images.githubusercontent.com/50013971/200354745-757c7396-3eb3-4b42-a6e7-d649f4ae51cf.png">

How can I push View above tabView, not inside?
<img width="484" alt="image" src="https://user-images.githubusercontent.com/50013971/200354705-1f4ade25-2d6b-4780-894a-79102ce857a8.png">

Please help)

**Comment by frzi** [comment]
This is actually very easy 🙂  All you need to do is put the entire tabView into another route.

E.g. if we have the `ContentView`:
```swift
struct ContentView: View {
	var body: some View {
		SwitchRoutes {
			Route("/settings/*", content: SettingsView())
			Route {
				ViewWithTabs() // <--- the 'tab view'
			}
		}
	}
}
```

We have a route that renders `SettingsView` for the path `"/settings/*"`. For any other path the `ViewWithTabs` (in this case the so-called tabView) will be rendered.

Then, somewhere in `ViewWithTabs` (maybe as a tab itself) you need a `NavLink` that redirects to an absolute path (in this case `"/settings"`):
```swift
NavLink(to: "/settings") {
	VStack {
		Image(systemName: "gears")
		Text("Settings")
	}
}
```

In this case the entire `ViewWithTabs` will be replaced with the `SettingsView`, and thus allowing an entirely different flow of routing.

**Comment by IlyasNN** [comment]
Is there a way how I can save state of tabTab views with it's tabs' contents?

**Comment by frzi** [comment]
Sadly not automatically, no. You will need to come up with your own solution. (Maybe an environment object) This is a challenge you will face very often in SwiftUI 🙂

**Comment by IlyasNN** [comment]
It's very sad( 
Anyway, thank you for fast answer. I suppose this issue can be closed
