### ISSUE TITLE
Add Installation instructions

### ISSUE THREAD

**Issue by BorntraegerMarc** [frzi/SwiftUIRouter#9]
Would be nice for beginners (like me) how to install this swift package

**Comment by BorntraegerMarc** [comment]
OK, so apparently one can follow [these instructions](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app) & then under `File > Swift Packages > Add Package Dependency` enter the repository URL https://github.com/frzi/SwiftUIRouter

**Comment by frzi** [comment]
That's correct. The ability to add Swift Packages in Xcode was added last year in Xcode 11. Before that, Swift Packages weren't supported by Xcode at all and had to be installed via command line. 😄
